name: Create release
run-name: ${{ format('Create {0} release', inputs.version_type) }}

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: "Version type"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  publish:
    name: Publish release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Exit early if not on 1.x
        if: github.ref != 'refs/heads/1.x'
        run: exit 1

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.NIGHTWATCH_PERMISSIONS_APP_ID }}
          private-key: ${{ secrets.NIGHTWATCH_PERMISSIONS_APP_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Bump version
        shell: bash
        id: bump-version
        run: |
          IFS="."
          version_type=${{ inputs.version_type }}
          current_version=$(cat version.txt)

          if [[ $current_version =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
              major=${BASH_REMATCH[1]}
              minor=${BASH_REMATCH[2]}
              patch=${BASH_REMATCH[3]}

            case "$version_type" in
              major)
                major=$((major + 1))
                minor=0
                patch=0
                ;;
              minor)
                minor=$((minor + 1))
                patch=0
                ;;
              patch)
                patch=$((patch + 1))
                ;;
            esac

            echo "Bumping ${version_type} version"
            echo "Was: ${current_version}"

            new_version="$major.$minor.$patch"
            echo "version=$new_version" >> "$GITHUB_OUTPUT"
            echo "Now: ${new_version}"
            echo "${new_version}" > version.txt
          else
              echo "Current version format is invalid" >&2
              exit 1
          fi

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Bump version to v${{ steps.bump-version.outputs.version }}"
          tag: "v${{ steps.bump-version.outputs.version }}"
          push: true

      - name: Generate release notes
        id: notes
        uses: RedCrafter07/release-notes-action@main
        with:
          tag-name: v${{ steps.bump-version.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "1.x"

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          release-notes: ${{ steps.notes.outputs.release-notes }}
          latest-version: "v${{ github.event.release.tag_name }}"
          compare-url-target-revision: "1.x"
          parse-github-usernames: true

      - uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: false
          body: ${{ steps.notes.outputs.release-notes }}
          make_latest: true
          name: "v${{ steps.bump-version.outputs.version }}"
          tag_name: "v${{ steps.bump-version.outputs.version }}"
